version: '3.8'

services:
  instagram-downloader:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
    networks:
      - instagram-network

networks:
  instagram-network:
    driver: bridge
