[phases.setup]
nixPkgs = ["python3", "pip", "curl", "ffmpeg"]

[phases.install]
cmds = [
  "pip install yt-dlp",
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp",
  "chmod a+rx /usr/local/bin/yt-dlp"
]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "npm start"
